"""Application-facing ports implemented by infrastructure adapters."""

from app.application.ports.analyzers import (
    AnalyzedContradiction,
    AnalyzedFact,
    AnalyzedQuestion,
    AnalyzerErrorCode,
    AnalyzerRefusal,
    AnalyzerResult,
    AnalyzerSuccess,
    IntakeAnalyzer,
    IntakeAnalyzerError,
    StructuredIntake,
)
from app.application.ports.drafters import (
    DrafterErrorCode,
    DraftingRefusal,
    DraftingResult,
    DraftingSuccess,
    FakeFollowUpDrafter,
    FollowUpDrafter,
    FollowUpDrafterError,
)
from app.application.ports.repositories import (
    AnalysisRepository,
    AuditEventRepository,
    CaseRepository,
    DocumentMetadataRepository,
    FollowUpActiveAttemptError,
    FollowUpApprovalBlockedError,
    FollowUpCaseNotFoundError,
    FollowUpDecisionExistsError,
    FollowUpDraftExistsError,
    FollowUpDraftMissingError,
    FollowUpRepository,
    FollowUpStateChangedError,
    FollowUpVersionChangedError,
    SourceMessageRepository,
    ValidationRepository,
)

__all__ = [
    "AnalysisRepository",
    "AnalyzedContradiction",
    "AnalyzedFact",
    "AnalyzedQuestion",
    "AnalyzerErrorCode",
    "AnalyzerRefusal",
    "AnalyzerResult",
    "AnalyzerSuccess",
    "AuditEventRepository",
    "CaseRepository",
    "DocumentMetadataRepository",
    "DrafterErrorCode",
    "DraftingRefusal",
    "DraftingResult",
    "DraftingSuccess",
    "FakeFollowUpDrafter",
    "FollowUpActiveAttemptError",
    "FollowUpApprovalBlockedError",
    "FollowUpCaseNotFoundError",
    "FollowUpDecisionExistsError",
    "FollowUpDraftExistsError",
    "FollowUpDraftMissingError",
    "FollowUpDrafter",
    "FollowUpDrafterError",
    "FollowUpRepository",
    "FollowUpStateChangedError",
    "FollowUpVersionChangedError",
    "IntakeAnalyzer",
    "IntakeAnalyzerError",
    "SourceMessageRepository",
    "StructuredIntake",
    "ValidationRepository",
]
