"""Framework-independent domain model."""

from app.domain.entities import (
    AuditEvent,
    Case,
    ChecklistResult,
    Contradiction,
    DocumentMetadata,
    ExtractedFact,
    FollowUpDraft,
    IntakeAnalysis,
    ModelRun,
    ReviewDecision,
    SourceMessage,
    UnresolvedQuestion,
    ValidationFinding,
)
from app.domain.enums import (
    ActorType,
    AuditEventType,
    CaseStatus,
    ChecklistStatus,
    FactStatus,
    FindingSeverity,
    ModelRunPurpose,
    ModelRunStatus,
    OutputLanguage,
    ProcedureType,
    ReviewDecisionType,
)
from app.domain.errors import DomainError, DomainInvariantError, InvalidTransitionError
from app.domain.transitions import ALLOWED_TRANSITIONS, TransitionOutcome, transition_case

__all__ = [
    "ALLOWED_TRANSITIONS",
    "ActorType",
    "AuditEvent",
    "AuditEventType",
    "Case",
    "CaseStatus",
    "ChecklistResult",
    "ChecklistStatus",
    "Contradiction",
    "DocumentMetadata",
    "DomainError",
    "DomainInvariantError",
    "ExtractedFact",
    "FactStatus",
    "FindingSeverity",
    "FollowUpDraft",
    "IntakeAnalysis",
    "InvalidTransitionError",
    "ModelRun",
    "ModelRunPurpose",
    "ModelRunStatus",
    "OutputLanguage",
    "ProcedureType",
    "ReviewDecision",
    "ReviewDecisionType",
    "SourceMessage",
    "TransitionOutcome",
    "UnresolvedQuestion",
    "ValidationFinding",
    "transition_case",
]
